name: CraftCommand
version: '1.0.0'
main: winlyps.craftCommand.CraftCommand
api-version: '1.16'
authors: [ Winlyps ]
commands:
  craft:
    description: Opens the crafting table.
    usage: /craft
    permission: winlyps.craftcommand.use
    permission-message: You do not have permission to use this command.